# -*- coding: utf-8 -*-

import numpy as np
from scipy.ndimage import binary_dilation


def morphological_dilation(image_erode, labels_out, se):
    """
    The second morphological operation consists in that room spaces 
    are generated by applying a 3D morphological dilation on 
    individualised spaces without retrieving the continuity 
    generated by doorway spaces.

    Parameters
    ----------
    image_erode : ndarray of bools
        Erosion of the input by the structuring element.
    labels_out : numpy array
        Relabelling rooms.
    se : array_like
        Structuring element used for the erosion. Non-zero elements are 
        considered True. If no structuring element is provided, an element
        is generated with a square connectivity equal to one.

    Returns
    -------
    whole_dilated_image : numpy array 
        Dilation performed on individual segmented rooms.

    """
    # Structuring element
    se_dilatation = se
    
    # Unique labels rooms
    uni_lbls = np.unique(labels_out).tolist()
    
    # Allocating memory array to store individual dilation results
    whole_dilated_image = np.zeros_like(image_erode)
    
    # Dilation performed on individual segmented rooms
    for lbl in uni_lbls:
        if lbl != 0:
            individual_cluster_image = np.zeros_like(image_erode)
            individual_cluster_image[labels_out == lbl] = 1
            image_dilated = binary_dilation(individual_cluster_image, 
                                            structure=se_dilatation).astype(image_erode.dtype)
            whole_dilated_image[image_dilated == 1] = lbl

    return whole_dilated_image